server:
  port: 8083

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: user-service-route
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - RewritePath=/api/users/(?<segment>.*), /$\{segment}
            - id: notification-service-route
              uri: lb://notification-service
              predicates:
                - Path=/api/email/**
              filters:
                - RewritePath=/api/email/(?<segment>.*), /$\{segment}
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.netflix.discovery: INFO