server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

logging:
  level:
    org.springframework.cloud.config.server: TRACE
    org.springframework.boot: INFO
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"